### ISSUE TITLE
Cannot setup blockbot on a server with minimal mods

### ISSUE THREAD

**Issue by JAladwan** [QuiltServerTools/BlockBot#43]
So I'm setting up a new server using blockbot but when I try to start the server it hangs for a few seconds with an error finding a class and vomits out a massive stack trace about how main couldn't be found. Don't know if it's because one of the mods are incompatible but I installed blockbot with no issues about 6 months ago on a similar server with the same mods (they've been updated since then, though). Before installing blockbot the mods I installed were Carpet, CarpetExtra, Fabric Language Kotlin, Lithium, and Starlight. Here's a few snippets of the errors, I cropped out the rest because it's ridiculously long. Taking out blockbot starts up the server just fine.

`Error loading class: net/minecraft/class_5455$class_5457 (java.lang.ClassNotFoundException: net/minecraft/class_5455$class_5457)`

`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blockbot-discord'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]`

There's a few more errors, but I'm not sure if it's related to blockbot or just the other mods having issues running because of the previous errors. Can provide a full paste if more details are needed.

**Comment by JAladwan** [comment]
Using the build from the latest action allowed me to set up blockbot and start the server without any errors. Will report back if there are other problems.
